topdir=../
  
all:
	letce2 \
                lxc \
                build \
                bootstrap.cfg \
		../../templates/cfg/experiment.cfg \
		../../templates/cfg/container.cfg

clean:
	letce2 lxc clean

