topdir=../
  
all:
	letce2 \
                lxc \
                build \
                bootstrap.cfg \
		../../templates/common/experiment.cfg \
		../../templates/common/container.cfg

clean:
	letce2 lxc clean

